# Generated by Django 5.2.4 on 2025-07-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_llaves', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='administrators',
            options={'managed': True},
        ),
    ]
